@echo off
echo Activation de l'environnement virtuel...
call venv\Scripts\activate

echo Installation/Mise à jour des dépendances...
pip install -r requirements.txt

echo Lancement de l'application...
python Project_Manager_Gui.py

echo Désactivation de l'environnement virtuel...
deactivate
